# Autogenerated wrapper script for HelloWorldMPIC_jll for i686-linux-gnu-mpi+mpiabi
export hello_world

using CompilerSupportLibraries_jll
using MPIABI_jll
JLLWrappers.@generate_wrapper_header("HelloWorldMPIC")
JLLWrappers.@declare_executable_product(hello_world)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, MPIABI_jll, MPIPreferences)
    JLLWrappers.@init_executable_product(
        hello_world,
        "bin/hello_world",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
